# Generated by Django 5.0.6 on 2024-06-20 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='libros',
            name='ruta_img',
            field=models.TextField(default=''),
        ),
    ]
